
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PimSuite.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Chats
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int ChatToUserId { get; set; }

    public string Message { get; set; }

    public System.DateTime CreatedAt { get; set; }



    public virtual Users Users { get; set; }

    public virtual Users Users1 { get; set; }

}

}
